# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MxsusiXyV1VImuWkNszCX8dZW4MgmsL0
"""

import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import seaborn as sns
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier



b_cancer = datasets.load_breast_cancer() # it's source is same as : https://archive.ics.uci.edu/ml/datasets/wine



dir(b_cancer)

b_cancer.data

print(b_cancer.feature_names)
print(b_cancer.target_names)
print(b_cancer.target)

df = pd.DataFrame(data=b_cancer.data, columns=b_cancer.feature_names)
df.head()

df["target"] = b_cancer.target
df.head()

df.target.value_counts()

len(df)

X = df.drop(["target"], axis="columns")
y = df.target
print(X.head())
print(y.head())

linear_SVC_classifier = SVC(kernel='linear')
linear_SVC_classifier



